//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Model
{
    /// <summary>
    /// 实体类init_data。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("init_data")]
    [Serializable]
    public partial class init_data : Entity
    {
        #region Model
		private decimal? _event_id;
		private string _techical_data;
		private string _update_time;
		private string _create_data_time;
		private decimal? _detail_id;
		private decimal? _doubt;
		private string _date;
		private int _id;
		private string _events;
		private string _home;
		private string _away;
		private string _half_score;
		private string _score;
		private string _source_data;

		/// <summary>
		/// 
		/// </summary>
		[Field("event_id")]
		public decimal? event_id
		{
			get{ return _event_id; }
			set
			{
				this.OnPropertyValueChange("event_id");
				this._event_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("techical_data")]
		public string techical_data
		{
			get{ return _techical_data; }
			set
			{
				this.OnPropertyValueChange("techical_data");
				this._techical_data = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("update_time")]
		public string update_time
		{
			get{ return _update_time; }
			set
			{
				this.OnPropertyValueChange("update_time");
				this._update_time = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("create_data_time")]
		public string create_data_time
		{
			get{ return _create_data_time; }
			set
			{
				this.OnPropertyValueChange("create_data_time");
				this._create_data_time = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("detail_id")]
		public decimal? detail_id
		{
			get{ return _detail_id; }
			set
			{
				this.OnPropertyValueChange("detail_id");
				this._detail_id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("doubt")]
		public decimal? doubt
		{
			get{ return _doubt; }
			set
			{
				this.OnPropertyValueChange("doubt");
				this._doubt = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("date")]
		public string date
		{
			get{ return _date; }
			set
			{
				this.OnPropertyValueChange("date");
				this._date = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("id")]
		public int id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange("id");
				this._id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("events")]
		public string events
		{
			get{ return _events; }
			set
			{
				this.OnPropertyValueChange("events");
				this._events = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("home")]
		public string home
		{
			get{ return _home; }
			set
			{
				this.OnPropertyValueChange("home");
				this._home = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("away")]
		public string away
		{
			get{ return _away; }
			set
			{
				this.OnPropertyValueChange("away");
				this._away = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("half_score")]
		public string half_score
		{
			get{ return _half_score; }
			set
			{
				this.OnPropertyValueChange("half_score");
				this._half_score = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("score")]
		public string score
		{
			get{ return _score; }
			set
			{
				this.OnPropertyValueChange("score");
				this._score = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("source_data")]
		public string source_data
		{
			get{ return _source_data; }
			set
			{
				this.OnPropertyValueChange("source_data");
				this._source_data = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.id,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.id;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.event_id,
				_.techical_data,
				_.update_time,
				_.create_data_time,
				_.detail_id,
				_.doubt,
				_.date,
				_.id,
				_.events,
				_.home,
				_.away,
				_.half_score,
				_.score,
				_.source_data,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._event_id,
				this._techical_data,
				this._update_time,
				this._create_data_time,
				this._detail_id,
				this._doubt,
				this._date,
				this._id,
				this._events,
				this._home,
				this._away,
				this._half_score,
				this._score,
				this._source_data,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "init_data");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field event_id = new Field("event_id", "init_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field techical_data = new Field("techical_data", "init_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field update_time = new Field("update_time", "init_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field create_data_time = new Field("create_data_time", "init_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field detail_id = new Field("detail_id", "init_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field doubt = new Field("doubt", "init_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field date = new Field("date", "init_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id", "init_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field events = new Field("events", "init_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field home = new Field("home", "init_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field away = new Field("away", "init_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field half_score = new Field("half_score", "init_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field score = new Field("score", "init_data", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field source_data = new Field("source_data", "init_data", "");
        }
        #endregion
	}
}